// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Models;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20220224161238_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("En")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InListId")
                        .HasColumnType("integer");

                    b.Property<string>("Sv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InListId");

                    b.ToTable("Word", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            En = "apple",
                            InListId = -1,
                            Sv = "äpple"
                        },
                        new
                        {
                            Id = -2,
                            En = "poop",
                            InListId = -1,
                            Sv = "bajs"
                        },
                        new
                        {
                            Id = -3,
                            En = "demeanour",
                            InListId = -1,
                            Sv = "uppträdande"
                        });
                });

            modelBuilder.Entity("api.Models.WordList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WordList", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(2022, 2, 24, 16, 12, 38, 652, DateTimeKind.Utc).AddTicks(4102),
                            Name = "first"
                        });
                });

            modelBuilder.Entity("api.Models.Word", b =>
                {
                    b.HasOne("api.Models.WordList", "InList")
                        .WithMany("Words")
                        .HasForeignKey("InListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InList");
                });

            modelBuilder.Entity("api.Models.WordList", b =>
                {
                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
