// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Models;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20220222193220_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("en")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("inListId")
                        .HasColumnType("integer");

                    b.Property<string>("sv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("inListId");

                    b.ToTable("Word", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            en = "apple",
                            inListId = -1,
                            sv = "äpple"
                        },
                        new
                        {
                            Id = -2,
                            en = "poop",
                            inListId = -1,
                            sv = "bajs"
                        },
                        new
                        {
                            Id = -3,
                            en = "demeanour",
                            inListId = -1,
                            sv = "uppträdande"
                        });
                });

            modelBuilder.Entity("api.Models.WordList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WordList", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "first",
                            createdAt = new DateTime(2022, 2, 22, 19, 32, 20, 298, DateTimeKind.Utc).AddTicks(7981)
                        });
                });

            modelBuilder.Entity("api.Models.Word", b =>
                {
                    b.HasOne("api.Models.WordList", "inList")
                        .WithMany()
                        .HasForeignKey("inListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("inList");
                });
#pragma warning restore 612, 618
        }
    }
}
